name: ${project.plugin.name}
main: ${project.plugin.mainClass}
version: ${project.version}
description: ${project.description}
author: ${project.plugin.author}
website: ${project.url}
api-version: ${paper.api.version}

commands:
  plugin:
    description: Blocked command
  pl:
    description: Blocked command
  help:
    description: Blocked command
  bukkit:
    description: Blocked command
  '?':
    description: Blocked command
  pcommons:
    description: Prodrivers Commons main command
  hub:
    description: Prodrivers Commons' Hub teleportation command
    permission: pcommons.hub
  party:
    description: Prodrivers Commons' Party system interaction command
    permission: pcommons.party
  p:
    description: Prodrivers Commons' Party chat
    permission: pcommons.party

permissions:
  pcommons.hub:
    description: Allows one to enter to Prodrivers Commons-compatible sections.
    default: true
  pcommons.commandblocker.bypass:
    description: Allows one to executed blocked commands.
    default: op
  pcommons.party.help:
    description: Allows one to see party commands help.
    default: true
  pcommons.party.invite:
    description: Allows one to invite a player to its party.
    default: true
  pcommons.party.accept:
    description: Allows one to accept a party invitation.
    default: true
  pcommons.party.kick:
    description: Allows one to kick a player from its party.
    default: true
  pcommons.party.list:
    description: Allows one to list its party members.
    default: true
  pcommons.party.disband:
    description: Allows one to disband its party.
    default: true
  pcommons.party.leave:
    description: Allows one to leave its party.
    default: true
  pcommons.party.owner:
    description: Allows one to let its party to a new owner.
    default: true
  pcommons.party.chat:
    description: Allows one to chat with its party.
    default: true
  pcommons.sections.query:
    description: Allows one to see which section the player is in.
    default: op
  pcommons.reload:
    description: Allows one to reload Prodrivers Commons.
    default: op