package fr.prodrivers.bukkit.commons.parties;

public enum PartyMessage {
	DISBANDED,
	JOINED_YOU,
	JOINED_OTHERS,
	LEFT_YOU,
	LEFT_OTHERS,
	CANNOT_INVITE_YOURSELF,
	NOT_PARTY_OWNER_YOU,
	PLAYER_INVITED_INVITER,
	PLAYER_INVITED_YOU,
	PLAYER_IS_IN_PARTY,
	PARTY_LEAVE_BEFORE_JOINING_ANOTHER,
	PARTY_NOT_INVITED_YOU,
	PARTY_LEADER_ASSIGNED_YOU,
	PARTY_LEADER_ASSIGNED_OTHERS
}
